---
- name: Run timedatectl status
  command: /usr/bin/timedatectl status
  changed_when: False
  check_mode: no
  register: timedatectl_result

- name: Set timezone to {{ timezone }}
  command: timedatectl set-timezone {{ timezone }}
  register: set_timezone
  when: timezone not in timedatectl_result.stdout

- name: Printing out result is success
  debug:
    msg: "{{ timedatectl_result.stdout.find(timezone) }}"

- name: Set ntp sync
  command: timedatectl set-ntp true
  register: set_ntp
  when: "'NTP enabled: no' in timedatectl_result.stdout"
