---
- name: restart node_exporter
  become: true
  systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted

- name: Restart Consul Client
  systemd:
    name: consul-client
    state: restarted

- name: Restart Dnsmasq
  systemd:
    name: dnsmasq
    state: restarted

- name: Restart Fluentd Process
  become: true
  systemd:
    daemon_reload: true
    name: td-agent
    state: restarted

- name: Reload daemon
  systemd:
    name: td-agent
    daemon_reload: yes
